import puppeteer from 'puppeteer';
import { mkdirSync } from 'node:fs';

const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:4173/stadium.html', { waitUntil: 'domcontentloaded', timeout: 45000 });
await page.waitForSelector('#flow-diverted');
await page.click('#mode-toggle');
const baseline = await page.evaluate(() => ({ diverted: Number(document.querySelector('#flow-diverted').textContent), walk: document.querySelector('#flow-walk').textContent, queue: document.querySelector('#flow-queue').textContent }));
await page.select('#flow-template', 'west-close');
const westClosed = await page.evaluate(() => ({ diverted: Number(document.querySelector('#flow-diverted').textContent), walk: document.querySelector('#flow-walk').textContent, queue: document.querySelector('#flow-queue').textContent, blocked: document.querySelector('#flow-blocked').textContent, barrier: document.querySelector('.barrier-item')?.textContent }));
await page.select('#flow-template', 'slow');
const slow = await page.$eval('#flow-queue', (element) => element.textContent);
await page.select('#flow-template', 'open');
await page.click('[data-camera=parking]');
await new Promise((resolve) => setTimeout(resolve, 2000));
await page.click('#barrier-place');
await page.mouse.click(720, 312);
const placed = await page.evaluate(() => ({ message: document.querySelector('#barrier-status').textContent, count: document.querySelectorAll('.barrier-item').length, blocked: Number(document.querySelector('#flow-blocked').textContent), walk: document.querySelector('#flow-walk').textContent }));
await page.$eval('[data-barrier-name]', (input) => { input.value = 'Test closure'; input.dispatchEvent(new Event('change', { bubbles: true })); });
await page.$eval('[data-barrier-color]', (input) => { input.value = '#cc44aa'; input.dispatchEvent(new Event('change', { bubbles: true })); });
await page.select('[data-barrier-effect]', 'slow');
const edited = await page.evaluate(() => ({ name: document.querySelector('[data-barrier-name]').value, color: document.querySelector('[data-barrier-color]').value, effect: document.querySelector('[data-barrier-effect]').value }));
await page.click('[data-barrier-archive]');
const archived = await page.evaluate(() => ({ count: document.querySelectorAll('.barrier-item.archived').length, blocked: Number(document.querySelector('#flow-blocked').textContent) }));
await page.click('[data-barrier-archive]');
await page.click('[data-camera=venue3d]');
await new Promise((resolve) => setTimeout(resolve, 2500));
mkdirSync('output', { recursive: true });
await page.screenshot({ path: 'output/stadium-venue-3d.png' });
const venue3d = await page.evaluate(() => ({ view: document.querySelector('#map-view-label').textContent, building: document.querySelector('#building-status').textContent, height: Number(document.querySelector('#building-status').dataset.cameraHeight) }));
await page.click('[data-camera=parking]');
await new Promise((resolve) => setTimeout(resolve, 1300));
await page.click('#camera-closer');
await new Promise((resolve) => setTimeout(resolve, 5000));
await page.screenshot({ path: 'output/stadium-flow-3d.png' });
const close = await page.evaluate(() => ({ view: document.querySelector('#map-view-label').textContent, building: document.querySelector('#building-status').textContent, mapError: document.querySelector('#map-error').hidden ? '' : document.querySelector('#map-error').textContent }));
await page.reload({ waitUntil: 'domcontentloaded' });
await page.waitForSelector('#barrier-list .barrier-item');
const persisted = await page.$$eval('.barrier-item', (rows) => rows.length);
await browser.close();
console.log(JSON.stringify({ baseline, westClosed, slow, placed, edited, archived, venue3d, close, persisted, errors }, null, 2));
if (errors.length || baseline.diverted !== 0 || westClosed.diverted < 1 || westClosed.blocked !== '0' || westClosed.walk === baseline.walk || !westClosed.barrier?.includes('West perimeter') || Number.parseFloat(slow) <= Number.parseFloat(baseline.queue) || !placed.message.includes('placed') || placed.count !== 1 || !placed.message.includes('visitors affected') || edited.name !== 'Test closure' || edited.color !== '#cc44aa' || edited.effect !== 'slow' || archived.count !== 1 || archived.blocked !== 0 || venue3d.view !== '3D VENUE' || !venue3d.building.includes('3D:') || venue3d.height >= 400 || close.view !== 'CLOSE VIEW' || !close.building.includes('3D:') || close.mapError || persisted !== 1) process.exitCode = 1;
