import puppeteer from 'puppeteer';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { decodeScenario } from './shareState.js';

const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:4173/stadium.html', { waitUntil: 'domcontentloaded', timeout: 45000 });
await page.waitForSelector('#simple-route');
await new Promise((resolve) => setTimeout(resolve, 2400));
assert.equal(await page.$eval('body', (body) => body.dataset.mode), 'simple');
await page.select('#simple-route', 'west-south');
await page.select('#simple-scenario', 'west-close');
const changed = await page.evaluate(() => ({ route: document.querySelector('#simple-route').value, scenario: document.querySelector('#simple-scenario').value, diverted: Number(document.querySelector('#simple-diverted').textContent), blocked: Number(document.querySelector('#simple-blocked').textContent) }));
assert.equal(changed.route, 'west-south');
assert.equal(changed.scenario, 'west-close');
assert.ok(changed.diverted > 0);
await page.click('#share-demo');
const link = await page.$eval('#share-url', (input) => input.value);
assert.ok(link.startsWith('https://antonioevans.github.io/gods-eye-view/stadium.html?scenario='));
await page.click('[data-close=share-dialog]');
await page.click('#mode-toggle');
assert.equal(await page.$eval('body', (body) => body.dataset.mode), 'advanced');
await page.click('#mode-toggle');
await page.click('#simple-3d');
await new Promise((resolve) => setTimeout(resolve, 2500));
await page.mouse.move(603, 237);
const hover = await page.$eval('#map-tooltip', (element) => element.hidden ? '' : element.textContent);
assert.ok(hover.includes('Demo zone'));
await page.mouse.down();
await page.mouse.move(650, 260, { steps: 8 });
await page.mouse.up();
const movedZone = await page.evaluate(() => JSON.parse(localStorage.getItem('noble-citi-field-demo-v1'))?.zones.find((zone) => zone.id === 'south'));
assert.ok(movedZone && movedZone.lat !== 40.75610);
await page.click('#share-demo');
const movedLink = await page.$eval('#share-url', (input) => input.value);
assert.equal(decodeScenario(new URL(movedLink).search).zones.find((zone) => zone.id === 'south').lat, movedZone.lat);
await page.click('[data-close=share-dialog]');
mkdirSync('output', { recursive: true });
await page.screenshot({ path: 'output/stadium-simple.png' });
const receiver = await browser.createBrowserContext();
const shared = await receiver.newPage();
await shared.setViewport({ width: 1440, height: 900 });
shared.on('pageerror', (error) => errors.push(error.message));
await shared.goto(process.env.DEMO_URL ? movedLink : movedLink.replace('https://antonioevans.github.io/gods-eye-view/stadium.html', 'http://127.0.0.1:4173/stadium.html'), { waitUntil: 'domcontentloaded', timeout: 45000 });
await shared.waitForSelector('#simple-route');
const restored = await shared.evaluate(() => ({ mode: document.body.dataset.mode, route: document.querySelector('#simple-route').value, scenario: document.querySelector('#simple-scenario').value, diverted: Number(document.querySelector('#simple-diverted').textContent) }));
assert.equal(restored.mode, 'simple');
assert.equal(restored.route, 'west-south');
assert.equal(restored.scenario, 'west-close');
assert.equal(restored.diverted, changed.diverted);
await shared.click('#share-demo');
const restoredLink = await shared.$eval('#share-url', (input) => input.value);
assert.equal(decodeScenario(new URL(restoredLink).search).zones.find((zone) => zone.id === 'south').lat, movedZone.lat);
await shared.click('[data-close=share-dialog]');
await page.close();
await shared.setViewport({ width: 390, height: 844 });
await shared.reload({ waitUntil: 'domcontentloaded' });
await new Promise((resolve) => setTimeout(resolve, 4500));
await shared.screenshot({ path: 'output/stadium-simple-mobile.png', fullPage: true });
const mobile = await shared.evaluate(() => ({ width: document.documentElement.scrollWidth, mapVisible: document.querySelector('.map-shell').getBoundingClientRect().width === innerWidth, controlsVisible: getComputedStyle(document.querySelector('.simple-controls')).display !== 'none' }));
assert.equal(mobile.width, 390);
assert.equal(mobile.mapVisible, true);
assert.equal(mobile.controlsVisible, true);
assert.deepEqual(errors, []);
await browser.close();
console.log(JSON.stringify({ changed, hover, movedZone, restored, mobile, linkLength: movedLink.length, errors }, null, 2));
