import puppeteer from 'puppeteer';
import { mkdirSync } from 'node:fs';

const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:4173/stadium.html', { waitUntil: 'domcontentloaded', timeout: 45000 });
await page.waitForSelector('.zone-row', { timeout: 30000 });
await new Promise((resolve) => setTimeout(resolve, 8000));
mkdirSync('output', { recursive: true });
await page.screenshot({ path: 'output/stadium-demo.png', fullPage: true });
const initial = await page.evaluate(() => ({ title: document.title, zones: document.querySelectorAll('.zone-row').length, issues: document.querySelectorAll('.incident-card').length, weather: document.querySelector('#weather-source-status').textContent, mapError: document.querySelector('#map-error').hidden ? '' : document.querySelector('#map-error').textContent, canvas: !!document.querySelector('#globe canvas') }));
const before = await page.$eval('#metric-transactions', (element) => Number(element.textContent.replace(/,/g, '')));
await new Promise((resolve) => setTimeout(resolve, 1200));
const after = await page.$eval('#metric-transactions', (element) => Number(element.textContent.replace(/,/g, '')));
await page.click('#sim-play');
const pausedClock = await page.$eval('#sim-clock', (element) => element.textContent);
await new Promise((resolve) => setTimeout(resolve, 600));
const pauseHeld = await page.$eval('#sim-clock', (element, value) => element.textContent === value, pausedClock);
await page.$eval('#sim-scrubber', (element) => { element.value = '1800'; element.dispatchEvent(new Event('input', { bubbles: true })); });
const scrubbed = await page.$eval('#sim-clock', (element) => element.textContent === 'T+30:00');
await page.select('#tx-filter', 'Parking');
const filtered = await page.$$eval('.tx-row', (rows) => rows.length > 0 && rows.every((row) => row.textContent.includes('Parking')));
await page.click('[data-sort=amount]');
const sorted = await page.$eval('[data-sort=amount]', (element) => element.classList.contains('active'));
await page.click('[data-camera=parking]');
await page.click('#camera-closer');
const closeView = await page.$eval('#map-view-label', (element) => element.textContent === 'CLOSE VIEW');
await page.click('#tab-operations');
await page.click('#add-incident');
await page.type('#issue-form [name=title]', 'Demo radio check');
await page.click('#issue-form button[type=submit]');
const added = await page.$eval('#incident-list', (element) => element.textContent.includes('Demo radio check'));
await page.reload({ waitUntil: 'domcontentloaded' });
await page.waitForSelector('.incident-card');
await page.click('#tab-operations');
const persisted = await page.$eval('#incident-list', (element) => element.textContent.includes('Demo radio check'));
await page.click('#settings-open');
await page.type('#theme-search', 'paper');
await page.click('[data-theme-choice=paper]');
const themeChanged = await page.evaluate(() => document.documentElement.dataset.theme === 'paper');
await page.click('[data-close=settings-dialog]');
await new Promise((resolve) => setTimeout(resolve, 700));
await page.screenshot({ path: 'output/stadium-demo-light.png', fullPage: true });
await page.click('[data-edit-issue=demo-1]');
page.once('dialog', (dialog) => dialog.accept());
await page.click('#archive-issue');
await page.click('[data-filter=archived]');
const archivedVisible = await page.$eval('#incident-list', (element) => element.textContent.includes('Gate readiness check'));
await page.click('[data-restore-issue=demo-1]');
await page.click('[data-filter=open]');
const issueRestored = await page.$eval('#incident-list', (element) => element.textContent.includes('Gate readiness check'));
await page.click('[data-edit-zone=field]');
page.once('dialog', (dialog) => dialog.accept());
await page.click('#archive-zone');
const zoneArchived = await page.$$eval('.zone-row', (rows) => rows.length === 4);
await page.click('#settings-open');
await page.click('[data-restore-zone=field]');
const zoneRestored = await page.$$eval('.zone-row', (rows) => rows.length === 5);
page.once('dialog', (dialog) => dialog.accept());
await page.click('#reset-demo');
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
await new Promise((resolve) => setTimeout(resolve, 600));
await page.screenshot({ path: 'output/stadium-demo-mobile.png', fullPage: true });
const mobile = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, settingsVisible: document.querySelector('#settings-open').getBoundingClientRect().right <= innerWidth }));
await browser.close();
console.log(JSON.stringify({ initial, simulation: { before, after, pauseHeld, scrubbed, filtered, sorted, closeView }, added, persisted, themeChanged, archivedVisible, issueRestored, zoneArchived, zoneRestored, mobile, errors }, null, 2));
if (errors.length || !initial.canvas || initial.mapError || initial.zones !== 5 || initial.issues !== 3 || after <= before || !pauseHeld || !scrubbed || !filtered || !sorted || !closeView || !added || !persisted || !themeChanged || !archivedVisible || !issueRestored || !zoneArchived || !zoneRestored || mobile.width > 390 || !mobile.settingsVisible) process.exitCode = 1;
